version: '3'
name: tmwu_warehouse_api_dev
services:
  api:
    container_name: tmwu_warehouse_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '6001:6001'
    volumes:
      - '${CONFIG_PATH}:/config'
      - ./src:/app/src
    expose:
      - '6001'
