version: '3'
name: tmwu_warehouse_api_dev
services:
  api:
    container_name: tmwu_warehouse_api_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - '${CONFIG_PATH}:/config'
      - ./src:/app/src
      - ./certificates:/app/certificates
    expose:
      - '${PORT}'
